[tool.bumpversion]
current_version = "1.4.2"

[[tool.bumpversion.files]]
filename = "src/glassesTools/version.py"


[[tool.bumpversion.files]]
filename = "README.md"
search = "GlassesTools v{current_version}"
replace = "GlassesTools v{new_version}"